{
    "url": "https://api.github.com/repos/dask/dask/issues/5292",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/5292/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/5292/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/5292/events",
    "html_url": "https://github.com/dask/dask/issues/5292",
    "id": 482222149,
    "node_id": "MDU6SXNzdWU0ODIyMjIxNDk=",
    "number": 5292,
    "title": "ValueError of DataFrame.merge",
    "user": {
        "login": "sighingnow",
        "id": 7144772,
        "node_id": "MDQ6VXNlcjcxNDQ3NzI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7144772?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sighingnow",
        "html_url": "https://github.com/sighingnow",
        "followers_url": "https://api.github.com/users/sighingnow/followers",
        "following_url": "https://api.github.com/users/sighingnow/following{/other_user}",
        "gists_url": "https://api.github.com/users/sighingnow/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sighingnow/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sighingnow/subscriptions",
        "organizations_url": "https://api.github.com/users/sighingnow/orgs",
        "repos_url": "https://api.github.com/users/sighingnow/repos",
        "events_url": "https://api.github.com/users/sighingnow/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sighingnow/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 8,
    "created_at": "2019-08-19T10:09:45Z",
    "updated_at": "2021-10-13T02:19:38Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "The `DataFrame.join` cannot give the correct answer:\r\n\r\n```python\r\n>>> import dask.dataframe as dd\r\n>>>\r\n>>> df1 = pd.DataFrame([[1,3,3], [4,2,6], [7, 8, 9]], columns=['a1', 'a2', 'a3'])\r\n>>> df2 = pd.concat([df1+1, df1+2])\r\n>>>\r\n>>> df1.join(df2, how='left', on='a1', lsuffix='_l', rsuffix='_r')\r\n   a1  a1_l  a2_l  a3_l  a1_r  a2_r  a3_r\r\n0   1     1     3     3   5.0   3.0   7.0\r\n0   1     1     3     3   6.0   4.0   8.0\r\n1   4     4     2     6   NaN   NaN   NaN\r\n2   7     7     8     9   NaN   NaN   NaN\r\n>>>\r\n>>> ddf1 = dd.from_pandas(df1, npartitions=2)\r\n>>> ddf2 = dd.from_pandas(df2, npartitions=2)\r\n>>> ddf1.join(ddf2, how='left', on='a1', lsuffix='_l', rsuffix='_r').compute()\r\n```\r\n\r\nThe exception traceback:\r\n\r\n```python\r\nValueError                                Traceback (most recent call last)\r\n<ipython-input-40-8cf730a949a3> in <module>\r\n----> 1 ddf1.join(ddf2, how='left', on='a1', lsuffix='_l', rsuffix='_r').compute()\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)\r\n    173         dask.base.compute\r\n    174         \"\"\"\r\n--> 175         (result,) = compute(self, traverse=False, **kwargs)\r\n    176         return result\r\n    177\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)\r\n    444     keys = [x.__dask_keys__() for x in collections]\r\n    445     postcomputes = [x.__dask_postcompute__() for x in collections]\r\n--> 446     results = schedule(dsk, keys, **kwargs)\r\n    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])\r\n    448\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)\r\n     80         get_id=_thread_get_id,\r\n     81         pack_exception=pack_exception,\r\n---> 82         **kwargs\r\n     83     )\r\n     84\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)\r\n    489                         _execute_task(task, data)  # Re-execute locally\r\n    490                     else:\r\n--> 491                         raise_exception(exc, tb)\r\n    492                 res, worker_id = loads(res_info)\r\n    493                 state[\"cache\"][key] = res\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)\r\n    128         if exc.__traceback__ is not tb:\r\n    129             raise exc.with_traceback(tb)\r\n--> 130         raise exc\r\n    131\r\n    132     import pickle as cPickle\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)\r\n    231     try:\r\n    232         task, data = loads(task_info)\r\n--> 233         result = _execute_task(task, data)\r\n    234         id = get_id()\r\n    235         result = dumps((result, id))\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)\r\n    117         func, args = arg[0], arg[1:]\r\n    118         args2 = [_execute_task(a, cache) for a in args]\r\n--> 119         return func(*args2)\r\n    120     elif not ishashable(arg):\r\n    121         return arg\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/optimization.py in __call__(self, *args)\r\n   1057         if not len(args) == len(self.inkeys):\r\n   1058             raise ValueError(\"Expected %d args, got %d\" % (len(self.inkeys), len(args)))\r\n-> 1059         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\r\n   1060\r\n   1061     def __reduce__(self):\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/core.py in get(dsk, out, cache)\r\n    147     for key in toposort(dsk):\r\n    148         task = dsk[key]\r\n--> 149         result = _execute_task(task, cache)\r\n    150         cache[key] = result\r\n    151     result = _execute_task(out, cache)\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)\r\n    117         func, args = arg[0], arg[1:]\r\n    118         args2 = [_execute_task(a, cache) for a in args]\r\n--> 119         return func(*args2)\r\n    120     elif not ishashable(arg):\r\n    121         return arg\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/compatibility.py in apply(func, args, kwargs)\r\n    105     def apply(func, args, kwargs=None):\r\n    106         if kwargs:\r\n--> 107             return func(*args, **kwargs)\r\n    108         else:\r\n    109             return func(*args)\r\n\r\n/usr/local/lib/python3.7/site-packages/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)\r\n   4834             ):\r\n   4835                 raise ValueError(\r\n-> 4836                     \"The columns in the computed data do not match\"\r\n   4837                     \" the columns in the provided metadata\"\r\n   4838                 )\r\n\r\nValueError: The columns in the computed data do not match the columns in the provided metadata\r\n```",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/5292/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/5292/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}