{
    "url": "https://api.github.com/repos/dask/dask/issues/5263",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/5263/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/5263/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/5263/events",
    "html_url": "https://github.com/dask/dask/issues/5263",
    "id": 479737947,
    "node_id": "MDU6SXNzdWU0Nzk3Mzc5NDc=",
    "number": 5263,
    "title": "`DataFrame.values` doesn't work after reduction in `map_partitions`",
    "user": {
        "login": "lr4d",
        "id": 44430780,
        "node_id": "MDQ6VXNlcjQ0NDMwNzgw",
        "avatar_url": "https://avatars.githubusercontent.com/u/44430780?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lr4d",
        "html_url": "https://github.com/lr4d",
        "followers_url": "https://api.github.com/users/lr4d/followers",
        "following_url": "https://api.github.com/users/lr4d/following{/other_user}",
        "gists_url": "https://api.github.com/users/lr4d/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lr4d/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lr4d/subscriptions",
        "organizations_url": "https://api.github.com/users/lr4d/orgs",
        "repos_url": "https://api.github.com/users/lr4d/repos",
        "events_url": "https://api.github.com/users/lr4d/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lr4d/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2019-08-12T16:27:15Z",
    "updated_at": "2019-09-06T19:38:04Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "I don't know if this is to be expected, but the dask graph appears to break when a reduction is performed in the function passed to `map_partitions`.\r\n\r\nIt seems like the dask graph expects pd.DataFrames out of `map_partitions` and fails when that's not the case.\r\n\r\nCode example:\r\n```\r\nimport dask\r\nprint(dask.__version__)\r\n\r\nimport dask.dataframe as dd\r\nimport pandas as pd\r\n\r\ndf = pd.DataFrame({\"A\": [1, 2]})\r\nddf = dd.from_pandas(df, npartitions=1)\r\n\r\nmeta = (\"A\", \"int\")\r\nddf.map_partitions(lambda df: df[\"A\"].sum(), meta=meta).values.compute()\r\n```\r\n\r\nOutput:\r\n```\r\n2.2.0\r\nTraceback (most recent call last):\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3296, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-21-71ba78ae2b82>\", line 13, in <module>\r\n    ddf.map_partitions(lambda df: df[\"A\"].sum(), meta=meta).values.compute()\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/base.py\", line 175, in compute\r\n    (result,) = compute(self, traverse=False, **kwargs)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/base.py\", line 446, in compute\r\n    results = schedule(dsk, keys, **kwargs)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/threaded.py\", line 82, in get\r\n    **kwargs\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/local.py\", line 491, in get_async\r\n    raise_exception(exc, tb)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/compatibility.py\", line 130, in reraise\r\n    raise exc\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/local.py\", line 233, in execute_task\r\n    result = _execute_task(task, data)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py\", line 119, in _execute_task\r\n    return func(*args2)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/optimization.py\", line 1059, in __call__\r\n    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py\", line 149, in get\r\n    result = _execute_task(task, cache)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py\", line 119, in _execute_task\r\n    return func(*args2)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/compatibility.py\", line 107, in apply\r\n    return func(*args, **kwargs)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/core.py\", line 4829, in apply_and_enforce\r\n    df = func(*args, **kwargs)\r\n  File \"/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/methods.py\", line 274, in values\r\n    return df.values\r\nAttributeError: 'numpy.int64' object has no attribute 'values'\r\n```",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/5263/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/5263/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}