{
    "url": "https://api.github.com/repos/dask/dask/issues/4226",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/4226/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/4226/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/4226/events",
    "html_url": "https://github.com/dask/dask/issues/4226",
    "id": 382093595,
    "node_id": "MDU6SXNzdWUzODIwOTM1OTU=",
    "number": 4226,
    "title": "error while assigning label encoded values to column in dask dataframe",
    "user": {
        "login": "BParesh89",
        "id": 10656618,
        "node_id": "MDQ6VXNlcjEwNjU2NjE4",
        "avatar_url": "https://avatars.githubusercontent.com/u/10656618?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/BParesh89",
        "html_url": "https://github.com/BParesh89",
        "followers_url": "https://api.github.com/users/BParesh89/followers",
        "following_url": "https://api.github.com/users/BParesh89/following{/other_user}",
        "gists_url": "https://api.github.com/users/BParesh89/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/BParesh89/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/BParesh89/subscriptions",
        "organizations_url": "https://api.github.com/users/BParesh89/orgs",
        "repos_url": "https://api.github.com/users/BParesh89/repos",
        "events_url": "https://api.github.com/users/BParesh89/events{/privacy}",
        "received_events_url": "https://api.github.com/users/BParesh89/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        },
        {
            "id": 996497175,
            "node_id": "MDU6TGFiZWw5OTY0OTcxNzU=",
            "url": "https://api.github.com/repos/dask/dask/labels/good%20second%20issue",
            "name": "good second issue",
            "color": "5319e7",
            "default": false,
            "description": "Clearly described, educational, but less trivial than \"good first issue\"."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 6,
    "created_at": "2018-11-19T07:48:44Z",
    "updated_at": "2021-10-12T07:58:40Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "\r\n0\r\ndown vote\r\nfavorite\r\nI am facing error in label encoding features. To generate my case(Originally, i have imported a csv file in dask dataframe and after cleaning, it is left with 28 columns), I have created dask dataframe like below:\r\n\r\n```\r\nimport dask\r\nimport dask.dataframe as dd\r\nfrom dask_ml.preprocessing import LabelEncoder\r\n\r\ncountry = np.random.choice(['US','UK','IN'],1700000)\r\ndf = pd.DataFrame({'A':country,'B':range(1700000)})\r\nddf = dd.from_pandas(df,npartitions=2,sort=False)\r\n```\r\nThen I tried to label encode categorical columns like below :\r\n\r\n```\r\nle = LabelEncoder()\r\nddf = ddf.assign(A=dd.from_dask_array(le.fit_transform(ddf['A'])))\r\n```\r\nwhich threw following error :\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nValueError                                Traceback (most recent call last)\r\n<ipython-input-106-480a5e12886a> in <module>()\r\n     10 type(le.fit_transform(ddf['A']))\r\n     11 #ddf['A'] = dd.from_array(le.fit_transform(ddf['A']))\r\n---> 12 ddf = ddf.assign(A=dd.from_dask_array(le.fit_transform(ddf['A'])))\r\n\r\n/opt/conda/lib/python3.6/site-packages/dask/dataframe/core.py in assign(self, **kwargs)\r\n   2698         # Figure out columns of the output\r\n   2699         df2 = self._meta.assign(**_extract_meta(kwargs))\r\n-> 2700         return elemwise(methods.assign, self, *pairs, meta=df2)\r\n   2701 \r\n   2702     @derived_from(pd.DataFrame, ua_args=['index'])\r\n\r\n/opt/conda/lib/python3.6/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)\r\n   3277 \r\n   3278     from .multi import _maybe_align_partitions\r\n-> 3279     args = _maybe_align_partitions(args)\r\n   3280     dasks = [arg for arg in args if isinstance(arg, (_Frame, Scalar, Array))]\r\n   3281     dfs = [df for df in dasks if isinstance(df, _Frame)]\r\n\r\n/opt/conda/lib/python3.6/site-packages/dask/dataframe/multi.py in _maybe_align_partitions(args)\r\n    145     divisions = dfs[0].divisions\r\n    146     if not all(df.divisions == divisions for df in dfs):\r\n--> 147         dfs2 = iter(align_partitions(*dfs)[0])\r\n    148         return [a if not isinstance(a, _Frame) else next(dfs2) for a in args]\r\n    149     return args\r\n\r\n/opt/conda/lib/python3.6/site-packages/dask/dataframe/multi.py in align_partitions(*dfs)\r\n    101         raise ValueError(\"dfs contains no DataFrame and Series\")\r\n    102     if not all(df.known_divisions for df in dfs1):\r\n--> 103         raise ValueError(\"Not all divisions are known, can't align \"\r\n    104                          \"partitions. Please use `set_index` \"\r\n    105                          \"to set the index.\")\r\n```\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/4226/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/4226/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}