{
    "url": "https://api.github.com/repos/dask/dask/issues/6018",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/6018/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/6018/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/6018/events",
    "html_url": "https://github.com/dask/dask/issues/6018",
    "id": 582658443,
    "node_id": "MDU6SXNzdWU1ODI2NTg0NDM=",
    "number": 6018,
    "title": "Merging fails when merging on a column of extension dtype of the same size (Int32 and int32)",
    "user": {
        "login": "lionsardesai",
        "id": 1217072,
        "node_id": "MDQ6VXNlcjEyMTcwNzI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1217072?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lionsardesai",
        "html_url": "https://github.com/lionsardesai",
        "followers_url": "https://api.github.com/users/lionsardesai/followers",
        "following_url": "https://api.github.com/users/lionsardesai/following{/other_user}",
        "gists_url": "https://api.github.com/users/lionsardesai/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lionsardesai/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lionsardesai/subscriptions",
        "organizations_url": "https://api.github.com/users/lionsardesai/orgs",
        "repos_url": "https://api.github.com/users/lionsardesai/repos",
        "events_url": "https://api.github.com/users/lionsardesai/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lionsardesai/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2020-03-16T23:35:16Z",
    "updated_at": "2023-04-05T08:25:33Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "Ran across this issue after updating pandas version (1.0.2) and on latest dask (2.12.0). This feels similar to #5720 that was previously reported.\r\n\r\nA snippet to reproduce the issue:\r\n```\r\nimport pandas as pd\r\nfrom dask.dataframe.multi import merge\r\nimport dask.dataframe as dd\r\nimport dask as d\r\n\r\nprint(\"---versions for bug report---\")\r\nprint(f\"pandas version: {pd.__version__}\")\r\nprint(f\"dask version: {d.__version__}\")\r\n\r\ndf1 = pd.DataFrame(\r\n    {\"A\": pd.Series([1, 2, 3], dtype=\"Int32\"), \"B\": [1, 1, 3], \"C\": list(\"aab\")}\r\n)\r\ndf2 = pd.DataFrame(\r\n    {\"A\": pd.Series([1, 2, 3], dtype=\"int32\"), \"E\": [1, 1, 3], \"F\": list(\"aab\")}\r\n)\r\nddf1 = dd.from_pandas(df1, 1)\r\nddf2 = dd.from_pandas(df2, 2)\r\n\r\n# pure pandas merge works\r\nprint(\"pandas-only merge\")\r\nprint(df1.merge(df2, on=\"A\"))\r\nprint(\"dask merge\")\r\n# fails with ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.\r\nprint(merge(ddf1, ddf2, on=\"A\"))\r\nprint(ddf1.merge(ddf2, on=\"A\"))\r\n```\r\n\r\nPandas can merge on the column A with dtypes Int32 and int32 respectively on df1 and df2, however the dask-equivalents throw the following error:\r\n`ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.`\r\n\r\n<details>\r\n<summary>Full trace:</summary>\r\n<p>\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"tests/test_merge_issue.py\", line 29, in <module>\r\n    print(merge(ddf1, ddf2, on=\"A\"))\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/dataframe/multi.py\", line 493, in merge\r\n    indicator=indicator,\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/dataframe/multi.py\", line 324, in single_partition_join\r\n    meta = left._meta_nonempty.merge(right._meta_nonempty, **kwargs)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py\", line 7297, in merge\r\n    validate=validate,\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 88, in merge\r\n    return op.get_result()\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 643, in get_result\r\n    join_index, left_indexer, right_indexer = self._get_join_info()\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 862, in _get_join_info\r\n    (left_indexer, right_indexer) = self._get_join_indexers()\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 841, in _get_join_indexers\r\n    self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 1311, in _get_join_indexers\r\n    zipped = zip(*mapped)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 1309, in <genexpr>\r\n    for n in range(len(left_keys))\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 1901, in _factorize_keys\r\n    lk = ensure_int64(com.values_from_object(lk))\r\n  File \"pandas/_libs/algos_common_helper.pxi\", line 93, in pandas._libs.algos.ensure_int64\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/arrays/masked.py\", line 145, in __array__\r\n    return self.to_numpy(dtype=dtype)\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/arrays/masked.py\", line 127, in to_numpy\r\n    f\"cannot convert to '{dtype}'-dtype NumPy array \"\r\nValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.\r\n```\r\n\r\n\r\n</p>\r\n</details>",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/6018/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/6018/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}