[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/506315120",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-506315120",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 506315120,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwNjMxNTEyMA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-27T11:54:44Z",
        "updated_at": "2019-06-27T11:54:44Z",
        "author_association": "MEMBER",
        "body": "The immediate cause seems to be https://github.com/pandas-dev/pandas/issues/24318, which affects other issues too (https://github.com/dask/dask/issues/4643, https://github.com/dask/dask/issues/4307).\r\n\r\nWe should investigate working around it.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/506315120/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/506317835",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-506317835",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 506317835,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwNjMxNzgzNQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-27T12:04:31Z",
        "updated_at": "2019-06-27T12:04:31Z",
        "author_association": "MEMBER",
        "body": "Playing with it a bit. This may not be the best approach, but I wanted to check:\r\n\r\n```diff\r\ndiff --git a/dask/dataframe/shuffle.py b/dask/dataframe/shuffle.py\r\nindex 7cc7731c7..3244f1313 100644\r\n--- a/dask/dataframe/shuffle.py\r\n+++ b/dask/dataframe/shuffle.py\r\n@@ -530,6 +530,11 @@ def partitioning_index(df, npartitions):\r\n     partitions : ndarray\r\n         An array of int64 values mapping each record to a partition.\r\n     \"\"\"\r\n+    if df.empty:\r\n+        # TODO: series, index...\r\n+        # empty because no rows\r\n+        return df.reset_index(drop=True).astype('uint64')\r\n+\r\n     return hash_pandas_object(df, index=False) % int(npartitions)\r\n \r\n```\r\n\r\nhits a new error, \r\n\r\n```pytb\r\n~/sandbox/dask/dask/dataframe/core.py in apply_and_enforce(*args, **kwargs)\r\n   4831             # Need nan_to_num otherwise nan comparison gives False\r\n   4832             if not np.array_equal(\r\n-> 4833                 np.nan_to_num(meta.columns), np.nan_to_num(df.columns)\r\n   4834             ):\r\n   4835                 raise ValueError(\r\n\r\n~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)\r\n   5061         if (name in self._internal_names_set or name in self._metadata or\r\n   5062                 name in self._accessors):\r\n-> 5063             return object.__getattribute__(self, name)\r\n   5064         else:\r\n   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):\r\n\r\nAttributeError: 'Series' object has no attribute 'columns'\r\n```\r\n\r\nI don't plan to look into this further today. Are you interested in taking it up from here @antonDA?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/506317835/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/506803103",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-506803103",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 506803103,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwNjgwMzEwMw==",
        "user": {
            "login": "antonDA",
            "id": 25005600,
            "node_id": "MDQ6VXNlcjI1MDA1NjAw",
            "avatar_url": "https://avatars.githubusercontent.com/u/25005600?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/antonDA",
            "html_url": "https://github.com/antonDA",
            "followers_url": "https://api.github.com/users/antonDA/followers",
            "following_url": "https://api.github.com/users/antonDA/following{/other_user}",
            "gists_url": "https://api.github.com/users/antonDA/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/antonDA/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/antonDA/subscriptions",
            "organizations_url": "https://api.github.com/users/antonDA/orgs",
            "repos_url": "https://api.github.com/users/antonDA/repos",
            "events_url": "https://api.github.com/users/antonDA/events{/privacy}",
            "received_events_url": "https://api.github.com/users/antonDA/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-28T16:50:56Z",
        "updated_at": "2019-06-28T16:50:56Z",
        "author_association": "NONE",
        "body": "I think I get what you are trying to do here and I tried looking into this new error for a bit, but it is a bit too deep into Dask's inner workings for me, I am afraid. \r\n\r\nThe new error is related to the meta variable being an empty Pandas Series in the apply_and_enforce function in dataframe/core.py. After your workaround returns this empty DataFrame, the code tries to compare the columns of meta with the columns of this DataFrame. However, this doesn't work as meta is an empty Pandas Series, which doesn't have the attribute columns. I don't really have any idea how to proceed from here.\r\n\r\nI am sorry I can't be of more help.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/506803103/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/506803534",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-506803534",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 506803534,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwNjgwMzUzNA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-06-28T16:52:16Z",
        "updated_at": "2019-06-28T16:52:16Z",
        "author_association": "MEMBER",
        "body": "No worries. Thanks for looking. \n\n> On Jun 28, 2019, at 11:50, antonDA <notifications@github.com> wrote:\n> \n> I think I get what you are trying to do here and I tried looking into this new error for a bit, but it is a bit too deep into Dask's inner workings for me, I am afraid.\n> \n> The new error is related to the meta variable being an empty Pandas Series in the apply_and_enforce function in dataframe/core.py. After your workaround returns this empty DataFrame, the code tries to compare the columns of meta with the columns of this DataFrame. However, this doesn't work as meta is an empty Pandas Series, which doesn't have the attribute columns. I don't really have any idea how to proceed from here.\n> \n> I am sorry I can't be of more help.\n> \n> \u2014\n> You are receiving this because you commented.\n> Reply to this email directly, view it on GitHub, or mute the thread.\n",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/506803534/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/556474885",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-556474885",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 556474885,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU1NjQ3NDg4NQ==",
        "user": {
            "login": "chrysm",
            "id": 14128499,
            "node_id": "MDQ6VXNlcjE0MTI4NDk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/14128499?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chrysm",
            "html_url": "https://github.com/chrysm",
            "followers_url": "https://api.github.com/users/chrysm/followers",
            "following_url": "https://api.github.com/users/chrysm/following{/other_user}",
            "gists_url": "https://api.github.com/users/chrysm/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chrysm/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chrysm/subscriptions",
            "organizations_url": "https://api.github.com/users/chrysm/orgs",
            "repos_url": "https://api.github.com/users/chrysm/repos",
            "events_url": "https://api.github.com/users/chrysm/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chrysm/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-11-20T22:18:01Z",
        "updated_at": "2019-11-20T22:18:01Z",
        "author_association": "NONE",
        "body": "when calling\r\n`grps = docs.groupby(pd.Grouper(key='created_at', freq='D'))`\r\n\r\ni get the following error:\r\n```\r\n  File \"{*}lib/python3.7/site-packages/pandas/core/indexes/base.py\", line 1747, in is_monotonic_increasing\r\n    return self._engine.is_monotonic_increasing\r\n  File \"pandas/_libs/index.pyx\", line 195, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\r\n  File \"pandas/_libs/index.pyx\", line 211, in pandas._libs.index.IndexEngine._do_monotonic_check\r\n  File \"pandas/_libs/index.pyx\", line 228, in pandas._libs.index.IndexEngine._call_monotonic\r\n  File \"pandas/_libs/algos.pyx\", line 766, in pandas._libs.algos.is_monotonic\r\n  File \"{*}lib/python3.7/site-packages/dask/array/core.py\", line 1445, in __bool__\r\n    return bool(self.compute())\r\nValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/556474885/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/556487692",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-556487692",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 556487692,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU1NjQ4NzY5Mg==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-11-20T22:30:00Z",
        "updated_at": "2019-11-20T22:30:00Z",
        "author_association": "MEMBER",
        "body": "@chrysm do you have a reproducible example for creating `docs`? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/556487692/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/556488389",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-556488389",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 556488389,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU1NjQ4ODM4OQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-11-20T22:30:39Z",
        "updated_at": "2019-11-20T22:30:39Z",
        "author_association": "MEMBER",
        "body": "And do you think that you're seeing the same issue as the original? Seems like they're both ValueErrors, but they have different error messages.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/556488389/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/645409479",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-645409479",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 645409479,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY0NTQwOTQ3OQ==",
        "user": {
            "login": "Prithwee",
            "id": 30373414,
            "node_id": "MDQ6VXNlcjMwMzczNDE0",
            "avatar_url": "https://avatars.githubusercontent.com/u/30373414?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Prithwee",
            "html_url": "https://github.com/Prithwee",
            "followers_url": "https://api.github.com/users/Prithwee/followers",
            "following_url": "https://api.github.com/users/Prithwee/following{/other_user}",
            "gists_url": "https://api.github.com/users/Prithwee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Prithwee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Prithwee/subscriptions",
            "organizations_url": "https://api.github.com/users/Prithwee/orgs",
            "repos_url": "https://api.github.com/users/Prithwee/repos",
            "events_url": "https://api.github.com/users/Prithwee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Prithwee/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-06-17T14:29:08Z",
        "updated_at": "2020-06-17T14:29:08Z",
        "author_association": "NONE",
        "body": "Do we have a solution to use grouper on Dask dataframe now?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/645409479/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/645426741",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-645426741",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 645426741,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY0NTQyNjc0MQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-06-17T14:56:52Z",
        "updated_at": "2020-06-17T14:56:52Z",
        "author_association": "MEMBER",
        "body": "This issue is still open.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/645426741/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/658402083",
        "html_url": "https://github.com/dask/dask/issues/5012#issuecomment-658402083",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5012",
        "id": 658402083,
        "node_id": "MDEyOklzc3VlQ29tbWVudDY1ODQwMjA4Mw==",
        "user": {
            "login": "EldritchCrow",
            "id": 12042169,
            "node_id": "MDQ6VXNlcjEyMDQyMTY5",
            "avatar_url": "https://avatars.githubusercontent.com/u/12042169?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/EldritchCrow",
            "html_url": "https://github.com/EldritchCrow",
            "followers_url": "https://api.github.com/users/EldritchCrow/followers",
            "following_url": "https://api.github.com/users/EldritchCrow/following{/other_user}",
            "gists_url": "https://api.github.com/users/EldritchCrow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/EldritchCrow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/EldritchCrow/subscriptions",
            "organizations_url": "https://api.github.com/users/EldritchCrow/orgs",
            "repos_url": "https://api.github.com/users/EldritchCrow/repos",
            "events_url": "https://api.github.com/users/EldritchCrow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/EldritchCrow/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-07-14T20:40:59Z",
        "updated_at": "2020-07-14T20:40:59Z",
        "author_association": "NONE",
        "body": "I encountered this today. It's possible that the root issue arises in conditions related to the number of partitions and/or the length of the dataframe. I tried this with multiple different subsets of my data and there's no single chunk being included that causes the issue. Hope this is helpful.\r\n\r\nMy code:\r\n```\r\nimport dask.dataframe as dd\r\nimport pandas as pd\r\n\r\n# Get subset of data (3 files, ~0.25 million rows)\r\ndaf = dd.read_csv(\"subset*.csv\")\r\ndaf['nodeTime'] = dd.to_datetime(daf['nodeTime']).dt.tz_localize(None)\r\n# This runs fine and returns expected results\r\na = daf.groupby(['platform', 'informationID', pd.Grouper(key='nodeTime', freq=\"1d\")])['nodeID'].count().compute()\r\n\r\n# Get all data (8 files, ~13 million rows)\r\ndaf = dd.read_csv('*.csv')\r\ndaf['nodeTime'] = dd.to_datetime(daf['nodeTime']).dt.tz_localize(None)\r\n# This errors\r\na = daf.groupby(['platform', 'informationID', pd.Grouper(key='nodeTime', freq=\"1d\")])['nodeID'].count().compute()\r\n```\r\nHere is the error that pops out:\r\n```\r\nValueError: all keys need to be the same shape\r\n```\r\nPastebin with full traceback:\r\nhttps://pastebin.com/wQKLeYtt",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/658402083/reactions",
            "total_count": 2,
            "+1": 2,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]