[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/521868720",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-521868720",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 521868720,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMTg2ODcyMA==",
        "user": {
            "login": "mrocklin",
            "id": 306380,
            "node_id": "MDQ6VXNlcjMwNjM4MA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/306380?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mrocklin",
            "html_url": "https://github.com/mrocklin",
            "followers_url": "https://api.github.com/users/mrocklin/followers",
            "following_url": "https://api.github.com/users/mrocklin/following{/other_user}",
            "gists_url": "https://api.github.com/users/mrocklin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mrocklin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mrocklin/subscriptions",
            "organizations_url": "https://api.github.com/users/mrocklin/orgs",
            "repos_url": "https://api.github.com/users/mrocklin/repos",
            "events_url": "https://api.github.com/users/mrocklin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mrocklin/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-16T03:11:23Z",
        "updated_at": "2019-08-16T03:11:23Z",
        "author_association": "MEMBER",
        "body": "Googling that error message shows that it might be coming from something else, like a `to_datetime` call in Pandas (https://stackoverflow.com/questions/39992411/to-datetime-value-error-at-least-that-year-month-day-must-be-specified-pand) ?\r\n\r\nIt seems like there might be something else going on.  Maybe some empty data that Pandas doesn't like?  This might not be super easy to diagnose in isolation.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/521868720/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/521869737",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-521869737",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 521869737,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyMTg2OTczNw==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-16T03:18:36Z",
        "updated_at": "2019-08-16T03:18:36Z",
        "author_association": "CONTRIBUTOR",
        "body": "ok, then i expect to have lost 1 partition, not 17.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/521869737/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525169081",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525169081",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525169081,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTE2OTA4MQ==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-27T07:03:53Z",
        "updated_at": "2019-08-27T07:03:53Z",
        "author_association": "CONTRIBUTOR",
        "body": "I am currently using retries again to compensate for https://github.com/dask/s3fs/issues/218 and have not had dataloss yet. Closing this issue and will re-open if necessary.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525169081/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525261043",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525261043",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525261043,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTI2MTA0Mw==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-27T11:33:16Z",
        "updated_at": "2019-08-27T11:33:16Z",
        "author_association": "CONTRIBUTOR",
        "body": "Things were going so well for a while...once I started to try and read back in the data I am getting \r\n`UncompressError: Error while decompressing: invalid input`. I'm not sure whether this is retries fault or s3fs or what.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525261043/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525804350",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525804350",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525804350,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTgwNDM1MA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-28T15:45:29Z",
        "updated_at": "2019-08-28T15:46:42Z",
        "author_association": "MEMBER",
        "body": "OK, I have a (somewhat complicated, very fragile) test that exercises retries when the parquet write fails.\r\n\r\n```diff\r\ndiff --git a/dask/bytes/tests/test_s3.py b/dask/bytes/tests/test_s3.py\r\nindex 582434168..26cd7a6a8 100644\r\n--- a/dask/bytes/tests/test_s3.py\r\n+++ b/dask/bytes/tests/test_s3.py\r\n@@ -451,3 +451,37 @@ def test_get_pyarrow_fs_s3(s3):\r\n     pa = pytest.importorskip(\"pyarrow\")\r\n     fs = DaskS3FileSystem(anon=True)\r\n     assert isinstance(fs, pa.filesystem.FileSystem)\r\n+\r\n+\r\n+def test_partial_upload(s3):\r\n+    from unittest import mock\r\n+    distributed = pytest.importorskip(\"distributed\")\r\n+    dd = pytest.importorskip(\"dask.dataframe\")\r\n+    s3fs.__version__ = \"0.4.0\"\r\n+\r\n+    df = dd.demo.make_timeseries()\r\n+\r\n+    i = 0\r\n+\r\n+    def new_callable():\r\n+        def f(f, data, schema, compression=None, fmd=None):\r\n+            from fastparquet.writer import make_part_file\r\n+            nonlocal i\r\n+            i += 1\r\n+            if i == 4:\r\n+                raise ValueError(\"Failure!\")\r\n+\r\n+            return make_part_file(f, data, schema, compression, fmd)\r\n+        return f\r\n+\r\n+    filename = \"s3://{}/partial.parquet\".format(test_bucket_name)\r\n+    target = \"dask.dataframe.io.parquet.fastparquet.make_part_file\"\r\n+\r\n+    with mock.patch(target, new_callable=new_callable) as m:\r\n+        with distributed.Client(processes=False, n_workers=1) as c:\r\n+            dsk = df.to_parquet(\"s3://{}/partial.parquet\".format(test_bucket_name), compute=False)\r\n+            dsk.compute(retries=2)\r\n+            assert i > 0\r\n+\r\n+            result = dd.read_parquet(filename)\r\n+            dd.utils.assert_eq(result, df)\r\n```\r\n\r\nUnfortunately, that's passing. I'm going to adapt this until I can get things failing.\r\n\r\nI may also implement https://github.com/dask/s3fs/issues/103. It seems useful for detecting failures at write time, and hopefully not too difficult. (Though I should note, I don't yet see how s3fs / fastparquet can have an issue writing a partial file. It seems to be happening though).",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525804350/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525837201",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525837201",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525837201,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTgzNzIwMQ==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-28T17:11:51Z",
        "updated_at": "2019-08-28T17:12:20Z",
        "author_association": "CONTRIBUTOR",
        "body": "Some observations from my end in case they're useful. I'm currently in the middle of yet another re-run of my big etl job and for the first time ever i have yet to have a failure! At this point this is all hocus pocus and intuition but here's what i am thinking about my current configuration:\r\n\r\n- i have been careful to make sure my workers aren't running \"in the orange\" i wasn't getting out of memory errors before just orange but i wondered if memory pressure was causing sessions to get cleared more often\r\n- i am running with fsspec 0.4.3 very latest, latest boto and my patch of dask master #5335 (https://github.com/birdsarah/dask/commits/pass_compression_to_parquet_write).\r\n- when i ran with fsspec 0.4.3, latest boto, and latest dask it was a disaster 4 out of 4 days of data failed before i gave up - i'm currently 6 for 6 passed - i have 33 days total to run.\r\n- with latest dask having the compression bug i was submitting uncompressed data to s3 which meant partitions were 300mb going up rather than 70mb\r\n\r\nConsider making a test that is trying to stream on a much bigger file? Or it's infrequent and try running the test 10k times?\r\n\r\nOver the course of weeks that I've been having this issue it seems to have progressed from partitions lost to bytes in a partition lost (see #5333) but there are a lot of moving parts and i'm not sure what's changed. We may want to keep only this issue or #5333.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525837201/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525994695",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525994695",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525994695,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTk5NDY5NQ==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-29T02:26:32Z",
        "updated_at": "2019-08-29T02:26:32Z",
        "author_association": "CONTRIBUTOR",
        "body": "This update on s3fs issue may be useful to this issue: https://github.com/dask/s3fs/issues/218#issuecomment-525993907",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525994695/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/525995722",
        "html_url": "https://github.com/dask/dask/issues/5284#issuecomment-525995722",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5284",
        "id": 525995722,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUyNTk5NTcyMg==",
        "user": {
            "login": "birdsarah",
            "id": 1796208,
            "node_id": "MDQ6VXNlcjE3OTYyMDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1796208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/birdsarah",
            "html_url": "https://github.com/birdsarah",
            "followers_url": "https://api.github.com/users/birdsarah/followers",
            "following_url": "https://api.github.com/users/birdsarah/following{/other_user}",
            "gists_url": "https://api.github.com/users/birdsarah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/birdsarah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/birdsarah/subscriptions",
            "organizations_url": "https://api.github.com/users/birdsarah/orgs",
            "repos_url": "https://api.github.com/users/birdsarah/repos",
            "events_url": "https://api.github.com/users/birdsarah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/birdsarah/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-08-29T02:31:55Z",
        "updated_at": "2019-08-29T02:31:55Z",
        "author_association": "CONTRIBUTOR",
        "body": "One small update to the above, having seen that things were progressing well but slowly I switched up my cluster configuration to what I had before to speed things along so i undid the constraint of \"make sure my workers aren't running \"in the orange\"\" so I ran everything at just into the orange and had no errors.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/525995722/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]